USE [DatabaseExam]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NCI_ProductID]    Script Date: 17-06-2024 16:48:46 ******/
CREATE NONCLUSTERED INDEX [NCI_ProductID] ON [dbo].[Reviews]
(
	[ProductID] ASC
)
INCLUDE([ReviewID],[ReviewTitle],[UserID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

