USE [DatabaseExam]
GO

/****** Object:  Index [NCI_Rating]    Script Date: 30-05-2024 12:35:24 ******/
CREATE NONCLUSTERED INDEX [NCI_Rating] ON [dbo].[Ratings]
(
	[Rating] ASC
)
INCLUDE([RatingID],[RatingCount],[ProductID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


