USE [DatabaseExam]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NCI_Category]    Script Date: 30-05-2024 12:36:27 ******/
CREATE NONCLUSTERED INDEX [NCI_Category] ON [dbo].[Categories]
(
	[Category] ASC
)
INCLUDE([CategoryID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


